### ISSUE TITLE
It looks like precinct and office are swapped in 20141104__ks__general__gove__precinct

### ISSUE THREAD

**Issue by simonw** [openelections/openelections-data-ks#12]
https://github.com/openelections/openelections-data-ks/blob/eeee2dd53554c349250a6d6c9738bbf87740a51c/2014/20141104__ks__general__gove__precinct.csv

Example:

    county,precinct,office,district,party,candidate,votes
    Gove,Attorney General,Baker,,D,A J Kotich,73
    Gove,Attorney General,Grainfield,,D,A J Kotich,37

It looks like precinct and office are swapped.

**Comment by dwillis** [comment]
On it, thanks!
