### ISSUE TITLE
Convert 2017 U.S. House special election precinct results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-ks#14]
Using files from the [Kansas sources repo](https://github.com/openelections/openelections-sources-ks), parse precinct-level files from the following counties for the April 11, 2017 special election for U.S. House district 4:

- [x] Barber
- [x] Butler
- [x] Chautauqua
- [x] Comanche
- [x] Cowley
- [x] Edwards
- [x] Elk
- [x] Greenwood
- [x] Harper
- [x] Harvey
- [x] Kingman
- [ ] Kiowa
- [x] Pawnee
- [x] Pratt
- [x] Sedgwick
- [x] Stafford
- [x] Sumner

**Comment by jonrobinson2** [comment]
No data from Kiowa?

**Comment by dwillis** [comment]
It's in there, yes.
