### ISSUE TITLE
Should nil votes be treated like zero?

### ISSUE THREAD

**Issue by karpet** [openelections/openelections-data-ks#20]
e.g. https://github.com/openelections/openelections-data-ks/blob/master/2016/20161108__ks__general__dickinson__precinct.csv#L19

Not sure if that's an empty spot in the source files, or a missing `0` in the csv.

**Comment by dwillis** [comment]
In this case it should either be nil or we should remove the line entirely. That precinct isn't in the state Senate district in question.

**Comment by karpet** [comment]
Thanks @dwillis.

There are multiple rows in 2012, 2014, 2016 that are missing votes or precinct information. Mostly they seem to be summary data (e.g. total votes for the district), probably where data from the source files was preserved when it should not have been.

I can prep a single PR that removes these rows, if that is the preferred tactic for handling them. Right now my scripts just ignore them.

**Comment by dwillis** [comment]
Sure, happy to accept a PR removing those rows.

**Comment by karpet** [comment]
PR #22 should address this issue.
