### ISSUE TITLE
20161108__ks__general__edwards__precinct.csv doesn't have President vote

### ISSUE THREAD

**Issue by jonrobinson2** [openelections/openelections-data-ks#29]
Odd I know, but seems to be missing Presidential vote in all precincts.

**Comment by karpet** [comment]
The Edwards results are present in https://github.com/openelections/openelections-sources-ks/blob/master/2016%20general%20precinct/2016%20General%20Election%20-%20President%20Results%20by%20Precinct.xlsx but apparently haven't made it into the data-ks repo.

**Comment by dwillis** [comment]
This is fixed now.
