### ISSUE TITLE
Precinct names

### ISSUE THREAD

**Issue by karpet** [openelections/openelections-data-ks#33]
I am looking at the precinct names in `2016/20161108__ks__general__douglas__precinct.csv` and I am trying to understand where they are coming from. The presidential results source file in https://github.com/openelections/openelections-sources-ks/blob/master/2016%20general%20precinct/2016%20General%20Election%20-%20President%20Results%20by%20Precinct.xlsx for example, has nothing like this line:

```csv
Douglas,Prec 67-78,President,,write-in,Evan McMullin,3
```

I can't correlate `Prec 67-78` to any real precinct in Douglas county.

I can kind of squint and see how `Lawrence Precinct 46 S3` might be shortened to `Prec 46` but it is spelled out in the source xlsx file, so it makes me wonder: how was this `data-ks/2016/...` file created in the first place?

**Comment by karpet** [comment]
I've opened #34 to re-parse from the sources-ks original files.

I am genuinely interested in where the original data-ks files came from though, because there are obvious differences beyond the precinct names.

**Comment by mikegaughan** [comment]
So, when the courts drew the lines in 2012, they did not do it as cleanly as the Legislature would have. They divided some townships and precincts in ways that caused some to have multiple house and senate districts in one precinct. So Precinct 46 in Lawrence which votes at Southwest middle school, got divided between Kansas Senate 3 and Kansas Senate 2. So the clerk now has to produce two ballots for that precinct - one with the 2nd district race on it and one with the 3rd. The Legislature would have made precinct 46 all in one Senate district.

**Comment by karpet** [comment]
Thanks @mikegaughan that helps explain why Kansas precincts are named the way they are.

My issue here is that the data in this repository for 2016 (at least) uses precinct names that match neither the SOS's nor the County's, and that makes me wonder where they originated.

**Comment by mikegaughan** [comment]
Precinct 67-68 is not a precinct, it is a combination of two precincts, but Precinct 68 probably doesn't have any voters. Precinct 67 is Willow Springs Township. I don't know why they are combined.

**Comment by mikegaughan** [comment]
Although that was only for Evan McMullen write in count, not for any other results, right?

**Comment by dwillis** [comment]
@karpet So to answer your question about origins of the files like https://github.com/openelections/openelections-sources-ks/blob/master/2016%20general%20precinct/2016%20General%20Election%20-%20President%20Results%20by%20Precinct.xlsx, those are from the KS SOS office. They weren't posted online but you could get them by requesting them, and we used them when we couldn't get a copy of official certified results from a county.

**Comment by karpet** [comment]
@dwillis yes I got similar files from the SOS, so I was able to confirm that the sources-ks files are ok.

What I'm confused by are the data-ks files in this repo. Where did they originate? Not from the equivalent sources-ks files, based on the precinct names.

**Comment by karpet** [comment]
update: @dwillis and I chatted on slack and it appears the original data was in http://www.douglas-county.com/mycounty/voting-and-elections/docs/electionresults/electionresults_generalbyprec_2016.pdf but that pdf did not get saved to sources-ks
