### ISSUE TITLE
2014 results are wrong

### ISSUE THREAD

**Issue by karpet** [openelections/openelections-data-ks#51]
I am working through 2014 results and there are some systemic mistakes which make me suspicious of the whole.

For example, in Douglas county there are references to "Paul Davis" as the Democratic candidate for US Senate. He was not. He ran for Governor.

In the same file, for the Governor office the precinct vote counts are swapped for the Democrat and the Republican.

I have source files from the KS SOS and am going to reparse from source. I will try and preserve any totals in the originals per discussion in #39

**Comment by dwillis** [comment]
@karpet Hmm, thanks for the report. That's concerning.

**Comment by karpet** [comment]
I have started on this. I have 101 of 105 counties complete, but those were the easy ones. The remaining 4 are the populous counties (Johnson, Sedgwick, Shawnee and Wyandotte) that only produce PDF SOVC files. The SOS does not have tidy .xls for those. I am creating txt versions of the SOVC (see e.g. https://github.com/openelections/openelections-sources-ks/pull/12) and will write some parsers to turn those into CSV.

If that proves too difficult, I may just go back and resurrect the .csv data prior to #53 for just those 4 counties.

**Comment by karpet** [comment]
Resolved with #52 #53 #54
