### ISSUE TITLE
2018: Johnson County missing Vicki Schmidt's votes (Commissioner of Insurance)

### ISSUE THREAD

**Issue by BrianAmos** [openelections/openelections-data-ks#59]
There only look to be entries for her opponent in the general precinct file.

**Comment by dwillis** [comment]
@BrianAmos Interesting - the source file from KSSOS doesn't have Schmidt's results from Johnson. Will chase down, thanks.

**Comment by karpet** [comment]
The .xls on the KS SOS site has it though. Must be a bug in the original parsing. I can prep a patch from http://www.sos.ks.gov/elections/18elec/2018_General_Election_Commissioner_of_Insurance_Precinct_Level_Results.xlsx

**Comment by dwillis** [comment]
@karpet Oh, ok. I can pick this up. I think we must have an older copy of the source file from KSSOS.
