### ISSUE TITLE
Rice 2016 general results have 2 mistakes

### ISSUE THREAD

**Issue by nk9** [openelections/openelections-data-ks#6]
These two errors have been verified against the [official results PDF](https://github.com/openelections/openelections-sources-ks/blob/master/Rice/2016%20Rice%2C%20KS%20precinct-level%20election%20results.pdf).

```
==> 20161108__ks__general__rice__precinct.csv
ERROR: candidate total incorrect, line 183. 2979 != 2980
{'county': 'Rice', 'precinct': 'Total', 'office': 'U.S. Senate', 'district': '', 'party': 'R', 'candidate': 'Jerry Moran', 'votes': 2979}
ERROR: candidate total incorrect, line 270. 732 != 738
{'county': 'Rice', 'precinct': 'Total', 'office': 'U.S. House', 'district': 1.0, 'party': 'IND', 'candidate': 'Alan LaPolice', 'votes': 732}
```

**Comment by nk9** [comment]
We don't want to report this to the county? The provisionals are written in too, there could easily be a real error here.

**Comment by dwillis** [comment]
You're right. I jumped the gun a bit there.

**Comment by karpet** [comment]
Has the county been notified? I can do that if no one else has.

**Comment by dwillis** [comment]
@karpet Not that I know of, so go for it.

**Comment by karpet** [comment]
Called and emailed. Will report back.

**Comment by karpet** [comment]
I have not heard anything but think this can be closed having done our due diligence.
